@startuml
package Mapbender <<Frame>> {
  package ConfigurationBundle <<frame>> {
    package ConfigurationEntity <<frame>> {
      class DataItem <extends Entity> {
        + id: int
        + parentId: int
        # children: DataItem[] = null
        -- key/value --
        + type: String
        + key: String
        + value: String

        -- history --
        + creationDate: DateTime
        + user: User

        -- scope --
        + scope: String = 'global'
        --
        + toArray() : Array
      }
    }

    package ConfigurationComponent <<frame>> {
      class ConfigurationComponent <extends ContainerAware> {
        -- Symfony2 service name --
        **mapbender.configuration**
        --
        + getById( id, scope = 'global' ) : DataItem
        + getByKey( key, parentId = 0 ) : DataItem[]
        + getByPath( path = "/", parentId = 0) : DataItem[]
        + getChildren( id = 0) DataItem[]
        + getParent( id = 0) DataItem
        -- Save --
        + save(value: DataItem) : DataItem
        + saveByParent ( DataItem[] values, parentId = 0) : DataItem
        + saveByKey( key, value, parentId = 0, type = null) : DataItem
        -- Remove --
        + remove(DataItem config) : bool
        + removeById(int id) : bool
      }
    }
    package ConfigurationController <<frame>> {
      class ConfigurationController <extends ContainerController> {
        -- Symfony2 route name --
        /configuration/
        --
        GET /configuration/{id}:
        + getById( id, scope = 'global' ) : DataItem
        GET /configuration/{key}[/{parentId}]:
        + getByKey( key, parentId = 0 ) : DataItem[]
        GET /configuration/path/{path}[/{pid}]:
        + getByPath( path = "/", parentId = 0) : DataItem[]
        GET /configuration/children/{id}:
        + getChildren( id = 0) DataItem[]
        GET /configuration/parent/{id}:
        + getParent( id = 0) DataItem
        -- Save --
        POST values /configuration/{pid}
        + saveByParent ( DataItem[] values, parentId = 0) : DataItem
        POST value /configuration/{pid}[/{type}]
        + saveByKey( key, value, parentId = 0, type = null) : DataItem
        -- Remove --
        DELETE /configuration/{id}
        + removeById(int id) : bool
      }
    }
  }

  DataItem .. ConfigurationComponent
  ConfigurationController .. ConfigurationComponent
}

@enduml